# 3.
# Почему возникла ошибка? Объясните и исправьте, чтобы функция
# могла работать с данными на входе в примере с res.

def mult(q, w, e, r, t, y):
    return q + w + e + r + t + y
res = mult(1, 2, 3, 4, 5, 6)
print(res)